# pds/Cargo.toml
[package]
name = "pds"
version = "0.1.0"
edition = "2024"

[dependencies]
migration = { path = "../migration", package = "cacos-migration" }
sea-orm = { workspace = true }
tokio = { workspace = true }
camino = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
camino-tempfile = { workspace = true }
